### ISSUE TITLE
编译时报错undefined: io.ReadAll

### ISSUE THREAD

**Issue by TIANLI0** [Yiwen-Chan/ZeroBot-Plugin#28]
/root/go/pkg/mod/github.com/fumiama/!zero!bot-!plugin-!timer@v0.0.0-20210606075146-09f50acdb4de/timer.go:106:18: undefined: io.ReadAll

**Comment by fumiama** [comment]
建议升级一下go语言版本试试

**Comment by Yiwen-Chan** [comment]
action编译已更新到 `Go 1.16` ，测试能通过编译了
